reddit:
  hnswlib_HNSW:
    docker-tag: neurips23-concurrent-hnswlib_HNSW
    module: neurips23.concurrent.hnswlib_HNSW.hnswlib_HNSW
    constructor: hnswlib_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"maxConnection": 64, "efConstruction": 400}]
        query-args: |
          [{"ef":30}]

sift:
  hnswlib_HNSW:
    docker-tag: neurips23-concurrent-hnswlib_HNSW
    module: neurips23.concurrent.hnswlib_HNSW.hnswlib_HNSW
    constructor: hnswlib_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"maxConnection": 64, "efConstruction": 400}]
        query-args: |
          [{"ef":30}]
          
glove:
  hnswlib_HNSW:
    docker-tag: neurips23-concurrent-hnswlib_HNSW
    module: neurips23.concurrent.hnswlib_HNSW.hnswlib_HNSW
    constructor: hnswlib_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"maxConnection": 64, "efConstruction": 400}]
        query-args: |
          [{"ef":30}]

msong:
  hnswlib_HNSW:
    docker-tag: neurips23-concurrent-hnswlib_HNSW
    module: neurips23.concurrent.hnswlib_HNSW.hnswlib_HNSW
    constructor: hnswlib_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"maxConnection": 64, "efConstruction": 400}]
        query-args: |
          [{"ef":30}]

msturing-10M:
  hnswlib_HNSW:
      docker-tag: neurips23-concurrent-hnswlib_HNSW
      module: neurips23.concurrent.hnswlib_HNSW.hnswlib_HNSW
      constructor: hnswlib_HNSW
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"maxConnection": 64, "efConstruction": 400}]
          query-args: |
            [{"ef":30}]