sift:
  batch_size: 500
  write_ratio: 0.1
  random_mode: 0
  max_pts: 1000000
  1:
    operation: "initial"
    start: 0
    end: 1000
  2:
    operation: "insert_and_search"
    start: 1000
    end: 1000000
  3:
    operation: "search"
  gt_url: "none"

random-xs:
  batch_size: 500
  write_ratio: 0.1
  random_mode: 0
  max_pts: 1000000
  1:
    operation: "initial"
    start: 0
    end: 1000
  2:
    operation: "insert_and_search"
    start: 1000
    end: 1000000
  3:
    operation: "search"
  gt_url: "none"

msturing-10M-clustered:
  batch_size: 500
  write_ratio: 0.1
  random_mode: 0
  max_pts: 1000000
  1:
    operation: "initial"
    start: 0
    end: 1000
  2:
    operation: "insert_and_search"
    start: 1000
    end: 1000000
  3:
    operation: "search"
  gt_url: "none"

msturing-30M-clustered:
  batch_size: 500
  write_ratio: 0.1
  random_mode: 0
  max_pts: 1000000
  1:
    operation: "initial"
    start: 0
    end: 1000
  2:
    operation: "insert_and_search"
    start: 1000
    end: 3000000
  3:
    operation: "search"
  gt_url: "none"
