sift:
  faiss_HNSW:
    docker-tag: neurips23-concurrent-faiss_HNSW
    module: neurips23.concurrent.faiss_HNSW.faiss_HNSW
    constructor: faiss_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {"indexkey": "faiss"},
            {"faissIndexTag": "HNSW"},
            {"maxConnection": 64}
          ]
        query-args: |
          [
            {"ef":30}
          ]

random-xs:
  faiss_HNSW:
    docker-tag: neurips23-concurrent-faiss_HNSW
    module: neurips23.concurrent.faiss_HNSW.faiss_HNSW
    constructor: faiss_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {"indexkey": "faiss"},
            {"faissIndexTag": "HNSW"},
            {"maxConnection": 64}
          ]
        query-args: |
          [
            {"ef":30}
          ]
          
msturing-10M-clustered:
  faiss_HNSW:
    docker-tag: neurips23-concurrent-faiss_HNSW
    module: neurips23.concurrent.faiss_HNSW.faiss_HNSW
    constructor: faiss_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {"indexkey": "faiss"},
            {"faissIndexTag": "HNSW"},
            {"maxConnection": 64}
          ]
        query-args: |
          [
            {"ef":100}
          ]

msturing-30M-clustered:
  faiss_HNSW:
    docker-tag: neurips23-concurrent-faiss_HNSW
    module: neurips23.concurrent.faiss_HNSW.faiss_HNSW
    constructor: faiss_HNSW
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {"indexkey": "faiss"},
            {"faissIndexTag": "HNSW"},
            {"maxConnection": 64}
          ]
        query-args: |
          [
            {"ef":100}
          ]