reddit:
    cufe: 
      docker-tag: neurips23-concurrent-cufe
      module: neurips23.concurrent.cufe.cufe
      constructor: cufe
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

sift:
    cufe: 
      docker-tag: neurips23-concurrent-cufe
      module: neurips23.concurrent.cufe.cufe
      constructor: cufe
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

glove:
    cufe: 
      docker-tag: neurips23-concurrent-cufe
      module: neurips23.concurrent.cufe.cufe
      constructor: cufe
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]

msong:
    cufe: 
      docker-tag: neurips23-concurrent-cufe
      module: neurips23.concurrent.cufe.cufe
      constructor: cufe
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
