reddit:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

sift:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

glove:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]

msong:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]

random-xs:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "buildthreads":32}]
          query-args: |
            [{"Ls":50, "T":8}]

text2image-1M:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":500, "buildthreads":32}]
          query-args: |
            [{"Ls":30, "T":8},
             {"Ls":50, "T":8},
             {"Ls":70, "T":8},
             {"Ls":100, "T":8}]
