random-xs:
    diskann: 
      docker-tag: neurips23-concurrent-diskann
      module: neurips23.concurrent.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
