reddit:
    diskann: 
      docker-tag: neurips23-congestion-diskann
      module: neurips23.congestion.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

sift:
    diskann: 
      docker-tag: neurips23-congestion-diskann
      module: neurips23.congestion.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]

glove:
    diskann: 
      docker-tag: neurips23-congestion-diskann
      module: neurips23.congestion.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]

msong:
    diskann: 
      docker-tag: neurips23-congestion-diskann
      module: neurips23.congestion.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]

msturing-10M:
    diskann: 
      docker-tag: neurips23-congestion-diskann
      module: neurips23.congestion.diskann.diskann
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":100, "insert_threads":32, "consolidate_threads":32}]
          query-args: |
            [
             {"Ls":100, "T":32}]
