random-xs:
  candy_nsg:
    docker-tag: neurips23-streaming-candy_nsg
    module: neurips23.streaming.candy_nsg.candy_nsg
    constructor: candy_nsg
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "faiss"}]
        query-args: |
            [{"ef":30}]
msturing-10M-clustered:
  candy_nsg:
    docker-tag: neurips23-streaming-candy_nsg
    module: neurips23.streaming.candy_nsg.candy_nsg
    constructor: candy_nsg
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "LSHAPG"}]
        query-args: |
          [{"ef":30}]
